CREATE TABLE PROFESORES(
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    DNI CHAR(9) PRIMARY KEY,
    DIRECCION VARCHAR2(30),
    TITULO VARCHAR2(30),
    GANA NUMBER(8,2)
);
CREATE TABLE CURSOS(
    NOMBRE_CURSO VARCHAR2(30),
    COD_CURSO NUMBER PRIMARY KEY,
    DNI_PROFESOR CHAR(9),
    MAXIMO_ALUMNOS NUMBER(3),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS NUMBER(5),
    CONSTRAINT CURSOS_FK FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI) ON DELETE CASCADE
);
CREATE TABLE ALUMNOS(
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    DNI CHAR(9) PRIMARY KEY,
    DIRECCION VARCHAR2(30),
    SEXO VARCHAR2(2),
    FECHA_NACIMIENTO DATE,
    CURSO NUMBER,
    CONSTRAINT ALUMNOS_FK FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO) ON DELETE CASCADE,
    CONSTRAINT ALUMNOS_CH CHECK (SEXO IN ('H', 'M'))
);
INSERT INTO PROFESORES(NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, TITULO, GANA) VALUES ('JUAN', 'ARCH', 'LOPEZ','32432455', 'Puerta Negra, 4', 'Ing. Informática', 7500);
INSERT INTO PROFESORES(NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, TITULO, GANA) VALUES ('MARIA', 'OLIVIA', 'RUBIO','43215643', 'Juan Alfonso 32', 'Lda. Fil. Inglesa', 5400);
INSERT INTO CURSOS(NOMBRE_CURSO,COD_CURSO,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN, NUM_HORAS) VALUES ('Inglés Básico', 1, '43215643', 15, '11/01/00', '22-DIC-00', 120);
INSERT INTO CURSOS(NOMBRE_CURSO,COD_CURSO,DNI_PROFESOR,MAXIMO_ALUMNOS,FECHA_INICIO,FECHA_FIN, NUM_HORAS) VALUES ('Administración Linux', 2, '32432455', NULL, '01-SEP-00', NULL, 80);
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('Lucas', 'Manilva', 'Lopez', '123523', 'Alhamar, 3', 'H', '11/01/79', 1 );
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('Antonia', 'López', 'Alcantara', '2567567', 'Maniqui, 21', 'M', NULL, 2 );
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('Manuel', 'Alcantara', 'Pedros', '3123689', 'Julian, 2', 'H', NULL, 1 );
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('Jose', 'Perez', 'Caballar', '4896765', 'Jarcha,5', 'H', '02/03/77', 2 );
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('Sergio', 'Navas', 'Retal', '123522', NULL, 'H', NULL, 1);
UPDATE PROFESORES SET GANA = NULL WHERE DNI = 32432455;
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION, SEXO,FECHA_NACIMIENTO,CURSO) VALUES ('María', 'Jaén', 'Sevilla', '789678', 'Martos, 5', 'M', NULL, NULL);
UPDATE ALUMNOS SET FECHA_NACIMIENTO = '23/12/76' WHERE DNI = 2567567;
UPDATE ALUMNOS SET CURSO = 5 WHERE DNI = 2567567;
DELETE FROM PROFESORES WHERE NOMBRE LIKE 'LAURA' AND APELLIDO1 LIKE 'JIMENEZ';
CREATE TABLE NOMBRE_DE_ALUMNOS AS( SELECT NOMBRE||' '||APELLIDO1||' '||APELLIDO2 "ALUMNOS" FROM ALUMNOS);
DELETE FROM CURSOS WHERE COD_CURSO = 1;
ROLLBACK;
ALTER TABLE ALUMNOS ADD CONSTRAINT ALUMNOS_FK_B FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO) ON DELETE CASCADE;
UPDATE ALUMNOS SET FECHA_NACIMIENTO = '01/01/12' WHERE FECHA_NACIMIENTO = NULL;


