/*Ejercicio 1 */
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTE F FULL JOIN PRODUCTO P ON F.ID = P.ID_FABRICANTE;

/*Ejercicio 2 */
SELECT F.NOMBRE, P.NOMBRE
FROM FABRICANTE F LEFT JOIN PRODUCTO P ON F.ID = P.ID_FABRICANTE
WHERE P.NOMBRE IS NULL;

/* -------------------------------------------- */

/*Ejercicio 1 */
SELECT COUNT(NOMBRE)
FROM PRODUCTO;

/*Ejercicio 2 */
SELECT COUNT(NOMBRE)
FROM FABRICANTE;

/*Ejercicio 3 */
SELECT COUNT(DISTINCT(ID_FABRICANTE))
FROM PRODUCTO;

/*Ejercicio 4 */
SELECT AVG(PRECIO)
FROM PRODUCTO;

/*Ejercicio 5 */
SELECT MIN(PRECIO)
FROM PRODUCTO;

/*Ejercicio 6 */
SELECT MAX(PRECIO)
FROM PRODUCTO;

/*Ejercicio 7 */
SELECT NOMBRE, PRECIO
FROM PRODUCTO
WHERE PRECIO = (SELECT MIN(PRECIO) FROM PRODUCTO);

/*Ejercicio 8 */
SELECT NOMBRE, PRECIO
FROM PRODUCTO
WHERE PRECIO = (SELECT MAX(PRECIO) FROM PRODUCTO);

/*Ejercicio 9 */
SELECT SUM(PRECIO)
FROM PRODUCTO;

/*Ejercicio 10 */
SELECT COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Asus';

/*Ejercicio 11 */
SELECT AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Asus';

/*Ejercicio 12 */
SELECT MIN(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Asus';

/*Ejercicio 13 */
SELECT MAX(PR.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Asus';

/*Ejercicio 14 */
SELECT SUM(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Asus';

/*Ejercicio 15 */
SELECT MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO), COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON P.ID_FABRICANTE = F.ID
WHERE F.NOMBRE = 'Crucial';

/*Ejercicio 16 */
SELECT F.NOMBRE, COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
ORDER BY 2 DESC;

/*Ejercicio 17 */
SELECT F.NOMBRE, MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
ORDER BY 2 DESC;

/*Ejercicio 18 */
SELECT F.ID, MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO), COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.ID
HAVING AVG(PRECIO) > 200;

/*Ejercicio 19 */
SELECT F.NOMBRE, MAX(P.PRECIO), MIN(P.PRECIO), AVG(P.PRECIO), COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING AVG(PRECIO) > 200;

/*Ejercicio 20 */
SELECT COUNT(NOMBRE)
FROM PRODUCTO
WHERE PRECIO >= 180;

/*Ejercicio 21 */
SELECT F.NOMBRE, COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
WHERE P.PRECIO >= 180
GROUP BY F.NOMBRE;

/*Ejercicio 22 */
SELECT F.ID, AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.ID
ORDER BY 1;

/*Ejercicio 23 */
SELECT F.NOMBRE, AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
ORDER BY 1;

/*Ejercicio 24 */
SELECT F.NOMBRE, AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING AVG(P.PRECIO) >= 150;

/*Ejercicio 25 */
SELECT F.NOMBRE, COUNT(P.NOMBRE)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING COUNT(P.NOMBRE) >= 2;

/*Ejercicio 26 */
SELECT F.NOMBRE, COUNT(P.NOMBRE), AVG(P.PRECIO)
FROM PRODUCTO P JOIN FABRICANTE F ON F.ID = P.ID_FABRICANTE
GROUP BY F.NOMBRE
HAVING AVG(P.PRECIO) >= 220;