CREATE OR REPLACE VIEW VISTA1 AS 
    SELECT NUMEM, NOMEM, SALAR, COMIS 
    FROM EMPLEADOS
    WHERE NUMDE LIKE '111';
    
CREATE OR REPLACE VIEW VISTA2 AS
    SELECT MAX(SUM(SALAR))"MAXIMO SALARIO"
    FROM EMPLEADOS 
    GROUP BY NUMDE; 
    
SELECT NUMDE 
FROM EMPLEADOS 
WHERE NUMDE = (SELECT NUMDE FROM VISTA2);

SELECT NOMEM
FROM VISTA1
WHERE COMIS IS NOT NULL
ORDER BY 1;

INSERT INTO VISTA1 VALUES(999, 'RODOLFO', 999, 999);
DELETE FROM EMPLEADOS WHERE NUMEM =999;

CREATE OR REPLACE VIEW VISTA3 AS
    SELECT C.NOMCE, D.NOMDE
    FROM CENTROS C JOIN DEPARTAMENTOS D ON C.NUMCE=D.NUMCE;
    
SELECT VISTA3.NOMCE, DEPARTAMENTOS.PRESU
FROM VISTA3 JOIN DEPARTAMENTOS ON VISTA3.NOMDE = DEPARTAMENTOS.NOMDE
GROUP BY VISTA3.NOMCE;

INSERT INTO VISTA3 VALUES('SUCURSAL ECIJA', 200,20, 180, 'F', 20, 110,'CONTABILIDAD');
/*Hay demasiados valores, y no se inserta la vista*/
