/*ANA ESTEBAN BARRANQUERO*/
CREATE TABLE EQUIPO(
    CODIGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    ESTADIO VARCHAR2(50) DEFAULT 0,
    AFORO NUMBER(6),
    CIUDAD VARCHAR2(30)
);
ALTER TABLE EQUIPO ADD CONSTRAINT EQUI_NOM_UQ UNIQUE(NOMBRE);
ALTER TABLE EQUIPO ADD(NUM_TITULOS NUMBER);
ALTER TABLE EQUIPO DROP(CIUDAD);
ALTER TABLE EQUIPO ADD CONSTRAINT EQUI_NOM_CH CHECK (NOMBRE= UPPER(NOMBRE));
ALTER TABLE EQUIPO ADD(AÑO_FUNDACION NUMBER(4));
ALTER TABLE EQUIPO ADD CONSTRAINT EQUI_FUND_CH CHECK(AÑO_FUNDACION > 1890);
CREATE TABLE PRESIDENTE(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    APELLIDOS VARCHAR2(50),
    FECHA_ELECCION DATE,
    FECHA_NAC DATE,
    EQUIPO NUMBER UNIQUE,
    CONSTRAINT PRE_EQUI_FK FOREIGN KEY(EQUIPO) REFERENCES EQUIPO(CODIGO) ON DELETE CASCADE
);
CREATE TABLE PARTIDO(
    CODIGO NUMBER PRIMARY KEY,
    FECHA DATE,
    EQ_LOCAL NUMBER,
    EQ_VISITANTE NUMBER,
    CONSTRAINT PART_EQLOC_FK FOREIGN KEY(EQ_LOCAL) REFERENCES EQUIPO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT PART_EQVIS_FK FOREIGN KEY(EQ_VISITANTE) REFERENCES EQUIPO(CODIGO) ON DELETE CASCADE
);
ALTER TABLE PARTIDO ADD CONSTRAINT PART_FECH_CH CHECK(FECHA < '21/06' AND FECHA > '21/09'); 
CREATE TABLE JUGADOR(
    CODIGO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30),
    POSICION VARCHAR2(15),
    FECHA_NAC DATE
);
ALTER TABLE JUGADOR ADD CONSTRAINT JUG_POS_CH CHECK(POSICION IN('PORTERO', 'DEFENSA', 'CENTROCAMPISTA', 'DELANTERO'));
CREATE TABLE GOLES(
    COD_PARTIDO NUMBER,
    COD_JUGADOR NUMBER,
    MINUTO NUMBER(3),
    DESCRIPCION VARCHAR2(100),
    CONSTRAINT GOL_PK PRIMARY KEY(COD_PARTIDO, COD_JUGADOR),
    CONSTRAINT GOL_CODP_FK FOREIGN KEY(COD_PARTIDO) REFERENCES PARTIDO(CODIGO) ON DELETE CASCADE,
    CONSTRAINT GOL_CODJ_FK FOREIGN KEY(COD_JUGADOR) REFERENCES JUGADOR(CODIGO) ON DELETE CASCADE
);
ALTER TABLE GOLES ADD CONSTRAINT GOL_MIN_CH CHECK(MINUTO<=100);
DROP TABLE GOLES;
DROP TABLE JUGADOR;
DROP TABLE PARTIDO;
DROP TABLE PRESIDENTE;
DROP TABLE EQUIPO;