DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    COD_CLIENTE NUMBER PRIMARY KEY,
    NIF CHAR(9),
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(30),
    TLFN NUMBER(9),
    CIUDAD VARCHAR2(30)
);
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_TLF CHECK (REGEXP_LIKE(TLFN, '^[69][0-9]{8}$'));
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_DNI CHECK (REGEXP_LIKE(NIF, '^[0-9]{8}[A-Z]'));
DROP TABLE MATERIAL;
CREATE TABLE MATERIAL(
    COD_MATERIAL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    PRECIO NUMBER(6,2)
);
DROP TABLE OPERACION;
CREATE TABLE OPERACION(
    COD_OPERACION NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(50),
    HORAS NUMBER(2)
);
ALTER TABLE OPERACION ADD CONSTRAINT OPERA_HORAS CHECK (HORAS<10);

DROP TABLE COCHE;
CREATE TABLE COCHE(
    MATRICULA CHAR(7) PRIMARY KEY,
    MARCA VARCHAR2(30),
    COLOR VARCHAR2(10),
    MODELO VARCHAR2(20),
    PVP NUMBER(8,2),
    COD_CLIENTE NUMBER,
    CONSTRAINT COCHE_CLIE_FK FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE) ON DELETE CASCADE
);
ALTER TABLE COCHE ADD CONSTRAINT COCHE_PVP_CHECK CHECK (PVP BETWEEN 10000 AND 40000);
ALTER TABLE COCHE ADD CONSTRAINT COCHE_MATRICULA CHECK (REGEXP_LIKE(MATRICULA,'^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE COCHE ADD CONSTRAINT COCHE_COLOR CHECK(COLOR IN('VERDE', 'ROJO', 'AZUL'));
ALTER TABLE COCHE ADD CONSTRAINT COCHE_MARCA CHECK(MARCA IS NOT NULL);
ALTER TABLE COCHE ADD CONSTRAINT COCHE_MODELO CHECK(MODELO IS NOT NULL);
DROP TABLE REVISION;
CREATE TABLE REVISION(
    COD_REVISION NUMBER PRIMARY KEY,
    FECHA DATE,
    MATRICULA CHAR(7),
    CONSTRAINT REV_MAT_FK FOREIGN KEY(MATRICULA) REFERENCES COCHE(MATRICULA) ON DELETE CASCADE
);
DROP TABLE NECESITA;
CREATE TABLE NECESITA(
    COD_MATERIAL NUMBER,
    COD_OPERACION NUMBER,
    CANTIDAD NUMBER,
    CONSTRAINT NECESITA_MAT_FK FOREIGN KEY(COD_MATERIAL) REFERENCES MATERIAL(COD_MATERIAL) ON DELETE CASCADE,
    CONSTRAINT NECESITA_OPE_FK FOREIGN KEY(COD_OPERACION) REFERENCES OPERACION(COD_OPERACION) ON DELETE CASCADE
);
DROP TABLE CONSTA_DE;
CREATE TABLE CONSTA_DE(
    COD_OPERACION NUMBER,
    COD_REVISION NUMBER,
    CONSTRAINT CONSTADE_OPER_FK FOREIGN KEY(COD_OPERACION) REFERENCES OPERACION(COD_OPERACION) ON DELETE CASCADE,
    CONSTRAINT CONSTADE_REV_FK FOREIGN KEY(COD_REVISION) REFERENCES REVISION(COD_REVISION) ON DELETE CASCADE
);