/*ANA ESTEBAN BARRANQUERO*/
DROP VIEW LISTADO_COMERCIAL_PEDIDOS;
CREATE OR REPLACE VIEW LISTADO_COMERCIAL_PEDIDOS AS
    SELECT C.NOMBRE||' '|| C.APELLIDO1 ||' '|| C.APELLIDO2 "COMERCIALES",CL.CIUDAD, P.ID, P.FECHA
    FROM CLIENTE CL  RIGHT JOIN PEDIDO P ON CL.ID = P.ID_CLIENTE RIGHT JOIN COMERCIAL C ON P.ID_COMERCIAL = C.ID;

SELECT COMERCIALES
FROM LISTADO_COMERCIAL_PEDIDOS
WHERE ID IS NULL;

SELECT *
FROM LISTADO_COMERCIAL_PEDIDOS
WHERE COMERCIALES LIKE 'Daniel Saez Vega';

SELECT COMERCIALES
FROM LISTADO_COMERCIAL_PEDIDOS  LCP JOIN PEDIDO P ON LCP.ID = P.ID
WHERE P.TOTAL > 2000;