/*ANA ESTEBAN BARRANQUERO*/
CREATE TABLE PERIODISTA(
    ID_PERIODISTA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    ESPECIALIDAD VARCHAR2(30)
);
CREATE SEQUENCE ID_PERIODISTA
INCREMENT BY 1
START WITH 1;

ALTER TABLE PERIODISTA ADD CONSTRAINT PER_NOM_CH CHECK(NOMBRE IS NOT NULL);

CREATE TABLE TELEFONOS_PERIODISTA(
    ID_PERIODISTA NUMBER,
    TELEFONO NUMBER(9) PRIMARY KEY,
    CONSTRAINT TEL_FK FOREIGN KEY(ID_PERIODISTA) REFERENCES PERIODISTA(ID_PERIODISTA) ON DELETE CASCADE
);
CREATE TABLE REVISTA(
    ID_REVISTA NUMBER PRIMARY KEY,
    PREIODICIDAD VARCHAR2(20),
    TITULO VARCHAR2(20),
    TIPO VARCHAR2(30)
);
CREATE SEQUENCE ID_REVISTA
INCREMENT BY 1
START WITH 1;

ALTER TABLE REVISTA ADD CONSTRAINT REV_NOM_CH CHECK(TITULO IS NOT NULL);
ALTER TABLE REVISTA ADD CONSTRAINT REV_PER_CH CHECK(PREIODICIDAD IN('SEMANAL', 'QUINCENAL', 'MENSUAL', 'TRIMESTRAL', 'ANUAL'));
ALTER TABLE REVISTA MODIFY PREIODICIDAD DEFAULT 'MENSUAL';
CREATE TABLE ESCRIBE(
    ID_PERIODISTA NUMBER,
    ID_REVISTA NUMBER,
    CONSTRAINT ESC_PK PRIMARY KEY(ID_PERIODISTA, ID_REVISTA),
    CONSTRAINT ESC_FKP FOREIGN KEY(ID_PERIODISTA) REFERENCES PERIODISTA(ID_PERIODISTA) ON DELETE CASCADE,
    CONSTRAINT ESC_FKR FOREIGN KEY(ID_REVISTA) REFERENCES REVISTA(ID_REVISTA) ON DELETE CASCADE
);
CREATE TABLE SUCURSAL(
    COD_SUCURSAL NUMBER PRIMARY KEY,
    DIRECCION VARCHAR2(50),
    TELEFONO NUMBER(9),
    CIUDAD VARCHAR2(50),
    PROVINCIA VARCHAR2(20)
);
CREATE SEQUENCE COD_SUCURSAL
INCREMENT BY 1
START WITH 1;
ALTER TABLE SUCURSAL ADD CONSTRAINT COD_SUC_CH CHECK(REGEXP_LIKE(COD_SUCURSAL, '`s[0-9][2,]$'));
CREATE TABLE PUBLICA(
    ID_REVISTA NUMBER,
    COD_SUCURSAL NUMBER,
    CONSTRAINT PUB_PK PRIMARY KEY(ID_REVISTA, COD_SUCURSAL),
    CONSTRAINT PUB_FKR FOREIGN KEY(ID_REVISTA) REFERENCES REVISTA(ID_REVISTA) ON DELETE CASCADE,
    CONSTRAINT PUB_FKCS FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL) ON DELETE CASCADE
);
CREATE TABLE EMPLEADO(
    ID_EMPELADO NUMBER PRIMARY KEY,
    COD_SUCURSAL NUMBER,
    NIF CHAR(9),
    NOMBRE VARCHAR2(15),
    APELLIDO1 VARCHAR2(20),
    APELLIDO2 VARCHAR2(20),
    TELEFONO NUMBER(9),
    CONSTRAINT EMPL_FK FOREIGN KEY(COD_SUCURSAL) REFERENCES SUCURSAL(COD_SUCURSAL) ON DELETE CASCADE
);
ALTER TABLE EMPLEADO ADD CONSTRAINT EM_NOM_CH CHECK(NOMBRE IS NOT NULL);
CREATE SEQUENCE ID_EMPELADO
INCREMENT BY 1
START WITH 1;

CREATE TABLE SECCION(
    ID_SECCION NUMBER PRIMARY KEY,
    ID_REVISTA NUMBER,
    DESCRIPCION VARCHAR2(50),
    TITULO VARCHAR2(50),
    CONSTRAINT SEC_FK FOREIGN KEY(ID_REVISTA) REFERENCES REVISTA(ID_REVISTA) ON DELETE CASCADE
);
CREATE SEQUENCE ID_SECCION
INCREMENT BY 1
START WITH 1;

CREATE TABLE EJEMPLAR(
    ID_EJEMPLAR NUMBER PRIMARY KEY,
    ID_REVISTA NUMBER,
    NUMERO_EJEMPLARES NUMBER(5),
    NUMERO_PAGINAS NUMBER(7),
    FECHA DATE,
    CONSTRAINT EJE_FK FOREIGN KEY(ID_REVISTA) REFERENCES REVISTA(ID_REVISTA) ON DELETE CASCADE
);
ALTER TABLE EJEMPLAR ADD CONSTRAINT EJE_NUM_PAG_CH CHECK(NUMERO_PAGINAS > 0);
ALTER TABLE EJEMPLAR ADD CONSTRAINT EJE_NUM_EJEM_CH CHECK(NUMERO_EJEMPLARES > 0);