CREATE TABLE COCHE(
    MATRICULA CHAR(7) PRIMARY KEY,
    MARCA VARCHAR2(10),
    MODELO VARCHAR2(10),
    COLOR VARCHAR2(10),
    PRECIOHORA NUMBER(5,2),
    CONSTRAINT MARC_NO_NULO_CK CHECK(MARCA IS NOT NULL),
    CONSTRAINT MOD_NO_NULO_CK CHECK(MODELO IS NOT NULL)
);
CREATE TABLE CLIENTE(
    CODCLIENTE NUMBER(4) PRIMARY KEY,
    DNI CHAR(9) UNIQUE,
    NOMBRE VARCHAR2(10),
    DIRECCION VARCHAR2(20),
    TELEFONO NUMBER(9),
    CONSTRAINT CLI_NO_NULO_CK CHECK(NOMBRE IS NOT NULL)
);
CREATE TABLE RESERVA(
    NUMERO NUMBER(4) PRIMARY KEY,
    FECHAINICIO DATE,
    FECHAFIN DATE,
    PRECIOTOTAL NUMBER(5,2),
    CODCLIENTE NUMBER(4),
    CONSTRAINT RES_CODC_FK FOREIGN KEY(CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE) ON DELETE CASCADE
);
CREATE TABLE AVALA(
    AVALADO NUMBER(4) PRIMARY KEY,
    AVALADOR NUMBER(4),
    CONSTRAINT AVA_AVLO_FK FOREIGN KEY(AVALADO) REFERENCES CLIENTE(CODCLIENTE) ON DELETE CASCADE,
    CONSTRAINT AVA_AVLOR_FK FOREIGN KEY(AVALADOR) REFERENCES CLIENTE(CODCLIENTE) ON DELETE CASCADE
);
CREATE TABLE INCLUYE(
    NUMERO NUMBER(4),
    MATRICULA CHAR(7),
    LITROSGAS NUMBER(5),
    CONSTRAINT INC_CLAVEP_PK PRIMARY KEY(NUMERO, MATRICULA),
    CONSTRAINT INC_NUM_FK FOREIGN KEY(NUMERO) REFERENCES RESERVA(NUMERO) ON DELETE CASCADE,
    CONSTRAINT INC_MAT_FK FOREIGN KEY(MATRICULA) REFERENCES COCHE(MATRICULA) ON DELETE CASCADE
);