CREATE TABLE REGION(
    CODREGION NUMBER(2) PRIMARY KEY,
    NOMBRE VARCHAR2(20)
);
CREATE TABLE PROVINCIA(
    CODPROVINCIA NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    CODREGION NUMBER(4),
    CONSTRAINT PROV_CODREG_FK FOREIGN KEY(CODREGION) REFERENCES REGION ON DELETE CASCADE
);
CREATE TABLE LOCALIDAD(
    CODLOCALIDAD  NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    CODPROVINCIA NUMBER(3),
    CONSTRAINT LOC_CODPROV_FK FOREIGN KEY(CODPROVINCIA) REFERENCES PROVINCIA ON DELETE CASCADE
);
CREATE TABLE EMPLEADO(
    ID NUMBER(4) PRIMARY KEY,
    DNI CHAR(9) UNIQUE,
    NOMBRE VARCHAR2(15),
    FECHANAC DATE,
    TELEFONO NUMBER(9),
    SALARIO NUMBER(5),
    CODLOCALIDAD NUMBER(3),
    CONSTRAINT EMP_CODLOC_FK FOREIGN KEY(CODLOCALIDAD) REFERENCES EMPLEADO ON DELETE CASCADE
);