CREATE TABLE ALUMNO(
    NUMMATRICULA VARCHAR2(9),
    NOMBRE VARCHAR2(20),
    FECHANACIMIENTO DATE,
    TELEFONO NUMBER(9),
    CONSTRAINT ALUM_CLAVEP_PK PRIMARY KEY(NUMMATRICULA)
);
CREATE TABLE RECIBE(
    NUMMATRICULA VARCHAR2(9),
    CODASIGNATURA NUMBER(3),
    CURSOESCOLAR NUMBER(4),
    CONSTRAINT REC_CLAVEP_PK PRIMARY KEY(NUMMATRICULA, CODASIGNATURA, CURSOESCOLAR),
    CONSTRAINT REC_NUMMAT_FK FOREIGN KEY(NUMMATRICULA) REFERENCES ALUMNO ON DELETE CASCADE,
    CONSTRAINT REC_CODASIG_FK FOREIGN KEY(CODASIGNATURA) REFERENCES ASIGNATURA ON DELETE CASCADE
);
CREATE TABLE ASIGNATURA(
    CODASIGNATURA NUMBER(3),
    NOMBRE VARCHAR2(30),
    IDPROFESOR NUMBER(2),
    CONSTRAINT ASI_CALVE_PK PRIMARY KEY(CODASIGNATURA),
    CONSTRAINT ASI_IDPROF_FK FOREIGN KEY(IDPROFESOR) REFERENCES PROFESOR ON DELETE CASCADE
);
CREATE TABLE PROFESOR(
    IDPROFESOR NUMBER(2),
    NIF_P VARCHAR(9),
    NOMBRE VARCHAR2(20),
    ESPECIALIDAD VARCHAR2(30),
    TELEFONO NUMBER(9),
    CONSTRAINT PROF_CLAVE_PK PRIMARY KEY(IDPROFESOR),
    CONSTRAINT PROF_NO_NULO_CK CHECK(NIF_P IS NOT NULL)
);
SELECT * FROM user_constraints where table_name='PROFESOR';