CREATE TABLE MONTADOR(
    NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(30),
    TELEFONO NUMBER(9)
);
CREATE TABLE MODELODORMITORIO(
    COD NUMBER(3) PRIMARY KEY
);
CREATE TABLE CLIENTE(
    NIF CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(30),
    TELEFONO NUMBER(9)
);
CREATE TABLE MONTA(
    MODELO NUMBER(3),
    NIF_M CHAR(9),
    FECHAMONTAJE DATE,
    CONSTRAINT MONT_CLAVEP_PK PRIMARY KEY(MODELO, NIF_M, FECHAMONTAJE),
    CONSTRAINT MONT_MOD_FK FOREIGN KEY(MODELO) REFERENCES MODELODORMITORIO(COD) ON DELETE CASCADE, 
    CONSTRAINT MONT_NIF_FK FOREIGN KEY(NIF_M) REFERENCES MONTADOR(NIF) ON DELETE CASCADE
);
CREATE TABLE COMPRA(
    NIF_C CHAR(9),
    MODELO NUMBER(3),
    FECHACOMPRA DATE,
    CONSTRAINT COMP_CLAVEP_PK PRIMARY KEY(NIF_C, MODELO, FECHACOMPRA),
    CONSTRAINT COMP_NIF_FK FOREIGN KEY(NIF_C) REFERENCES CLIENTE(NIF) ON DELETE CASCADE,
    CONSTRAINT COMP_MOD_FK FOREIGN KEY(MODELO) REFERENCES MODELODORMITORIO(COD) ON DELETE CASCADE
);