CREATE TABLE SUCURSAL(
    CODIGO NUMBER(4) PRIMARY KEY,
    DIRECCION VARCHAR2(20),
    TELEFONO NUMBER(9)
);
CREATE TABLE EMPLEADO(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    DIRECCION VARCHAR2(20),
    TELEFONO NUMBER(9),
    SUCURSAL NUMBER(4),
    CONSTRAINT EMP_SUC_FK FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO) ON DELETE CASCADE,
    CONSTRAINT EMP_NO_NULO_CK CHECK(NOMBRE IS NOT NULL)
);
CREATE TABLE PERIODISTA(
    DNI CHAR(9) PRIMARY KEY,
    NOMBRE VARCHAR2(10),
    DIRECCION VARCHAR2(20),
    TELEFONO NUMBER(9),
    ESPECIALISTA VARCHAR2(20),
    CONSTRAINT PER_NO_NULO_CK CHECK(NOMBRE IS NOT NULL)
);
CREATE TABLE REVISTA(
    NUMREG NUMBER(4) PRIMARY KEY,
    TITULO VARCHAR2(20),
    PERIODICIDAD VARCHAR2(20) DEFAULT 'MENSUAL',
    TIPO VARCHAR2(15),
    SUCURSAL NUMBER(4),
    CONSTRAINT REV_SUC_FK FOREIGN KEY(SUCURSAL) REFERENCES SUCURSAL(CODIGO) ON DELETE CASCADE,
    CONSTRAINT REV_NO_NULO_CK CHECK(TITULO IS NOT NULL),
    CONSTRAINT REV_PERIOCIDAD_CK CHECK(PERIODICIDAD IN('MENSUAL', 'QUINCENAL', 'SEMANAL', 'TRIMESTRAL', 'ANUAL'))
);
CREATE TABLE NUMREVISTA(
    NUMREG NUMBER(4),
    NUMERO NUMBER(4),
    NUMPAGINAS NUMBER(5),
    FECHA DATE,
    CANTVENDIDAS NUMBER(5),
    CONSTRAINT NUMREV_CLAVEP_PK PRIMARY KEY(NUMREG, NUMERO),
    CONSTRAINT NUMREV_NUMR_FK FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG) ON DELETE CASCADE,
    CONSTRAINT NUMR_MAYORQUE0_CK CHECK(NUMPAGINAS > 0)
);
CREATE TABLE ESCRIBE(
    NUMREG NUMBER(4),
    DNI_PER CHAR(9),
    CONSTRAINT ESCR_CLAVEP_PK PRIMARY KEY(NUMREG, DNI_PER),
    CONSTRAINT ESCR_NUMR_FK FOREIGN KEY(NUMREG) REFERENCES REVISTA(NUMREG) ON DELETE CASCADE,
    CONSTRAINT ESCR_DNI_FK FOREIGN KEY(DNI_PER) REFERENCES PERIODISTA(DNI) ON DELETE CASCADE
);
