CREATE TABLE DEPARTAMENTO(
    ID NUMBER(4) PRIMARY KEY,
    NOMBRE VARCHAR2(15),
    UBICACION VARCHAR2(30)
);
CREATE TABLE EMPLEADO(
    ID NUMBER(4) PRIMARY KEY,
    DNI CHAR(9) UNIQUE,
    NOMBRE VARCHAR(15),
    SALARIO NUMBER(6,2),
    TELEFONO NUMBER(9),
    IDDEP NUMBER(4),
    CONSTRAINT EMP_ID_FK FOREIGN KEY(IDDEP) REFERENCES DEPARTAMENTO(ID) ON DELETE CASCADE 
);
CREATE TABLE JEFE(
    ID NUMBER(4) PRIMARY KEY,
    DNI CHAR(9) UNIQUE,
    NOMBRE VARCHAR(15),
    SALARIO NUMBER(6,2),
    TELEFONO NUMBER(9),
    IDDEP NUMBER(4) UNIQUE,
    CONSTRAINT JEF_ID_FK FOREIGN KEY(IDDEP) REFERENCES DEPARTAMENTO(ID) ON DELETE CASCADE 
);