DECLARE
    NOMBRE VARCHAR2(25);
BEGIN
    NOMBRE:='&DIME_TU_NOMBRE:';
    DBMS_OUTPUT.PUT_LINE('HOLA '||NOMBRE);
   END;
/

DECLARE
    ALTURA NUMBER;
    BASE NUMBER;
BEGIN
    ALTURA:='&INTRODUCE_LA_ALTURA';
    BASE:='&INTRODUCE_LA_BASE';
    DBMS_OUTPUT.PUT_LINE('UN TRIANGULO DE BASE: '||BASE||' Y ALTURA '||ALTURA);
    DBMS_OUTPUT.PUT_LINE('TIENE UN AREA DE:'||(BASE*ALTURA)/2); 
END;
/

DECLARE
    A NUMBER:=50;
    B NUMBER:=10;
BEGIN
    DBMS_OUTPUT.PUT_LINE(A||' + '||B|| ' = '||(A+B));
    DBMS_OUTPUT.PUT_LINE(A||' - '||B|| ' = '||(A-B));
    DBMS_OUTPUT.PUT_LINE(A||' * '||B|| ' = '||(A*B));
    DBMS_OUTPUT.PUT_LINE(A||' / '||B|| ' = '||(A/B));
END;
/    