DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(
    DNI CHAR(9),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(15),
    LOCALIDAD VARCHAR2(30),
    FECHANAC DATE,
    SEXO VARCHAR2(10)
);
ALTER TABLE CLIENTE ADD CONSTRAINT CLIE_DNI_PK PRIMARY KEY(DNI);
DROP TABLE SUCURSAL;
CREATE TABLE SUCURSAL(
    CODSUCURSAL NUMBER(4),
    NOMBRE VARCHAR2(15),
    DIRECCION VARCHAR2(15),
    LOCALIDAD VARCHAR2(30)
);
ALTER TABLE SUCURSAL ADD CONSTRAINT SUC_COD_PK PRIMARY KEY(CODSUCURSAL);
DROP TABLE CUENTA;
CREATE TABLE CUENTA(
    CODSUCURSAL NUMBER(4),
    CODCUENTA NUMBER(4)
);
ALTER TABLE CUENTA ADD CONSTRAINT CUEN_CLAVE_PK PRIMARY KEY(CODSUCURSAL, CODCUENTA);
ALTER TABLE CUENTA ADD CONSTRAINT CUEN_CLAVE_FK FOREIGN KEY(CODSUCURSAL) 
REFERENCES SUCURSAL ON DELETE CASCADE;
DROP TABLE TRANSACCION;
CREATE TABLE TRANSACCION(
    CODSUCURSAL NUMBER(4),
    CODCUENTA NUMBER(4),
    NUMTRANSACCION NUMBER(4),
    FECHA DATE,
    CANTIDAD NUMBER(7),
    TIPO VARCHAR2(15)
);
ALTER TABLE TRANSACCION ADD CONSTRAINT TRANS_CLAVE_PK PRIMARY KEY(CODSUCURSAL, CODCUENTA, NUMTRANSACCION);
ALTER TABLE TRANSACCION ADD CONSTRAINT TRANS_CLAVE_FK FOREIGN KEY(CODSUCURSAL, CODCUENTA) 
REFERENCES CUENTA ON DELETE CASCADE;
DROP TABLE CLI_CUENTA;
CREATE TABLE CLI_CUENTA(
    CODSUCURSAL NUMBER(4),
    CODCUENTA NUMBER(4),
    DNI CHAR(9)
);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT CLI_CLAVE_PK PRIMARY KEY(CODSUCURSAL,CODCUENTA,DNI);
ALTER TABLE CLI_CUENTA ADD CONSTRAINT CLI_CLAVE_FK FOREIGN KEY(CODSUCURSAL,CODCUENTA) 
REFERENCES CUENTA ON DELETE CASCADE;
ALTER TABLE CLI_CUENTA ADD CONSTRAINT CLIE_CLAVE_FK FOREIGN KEY(DNI) 
REFERENCES CLIENTE ON DELETE CASCADE;

CREATE INDEX NOMBRE_DE_SUCURSAL ON SUCURSAL(NOMBRE);
CREATE INDEX NOMBRE_DE_CLIENTE ON CLIENTE(NOMBRE);
CREATE INDEX LOCALIDAD_DE_CLIENTE ON CLIENTE(LOCALIDAD);
CREATE INDEX LOCALIDAD_DE_SUCURSAL ON SUCURSAL(LOCALIDAD);
CREATE SEQUENCE CODSUCURSAL
INCREMENT BY 1
START WITH 1;