DROP TABLE TIENDAS;
CREATE TABLE TIENDAS (
    NIF VARCHAR2(10),
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20),
    CODPOSTAL NUMBER(5)
);
ALTER TABLE TIENDAS ADD CONSTRAINT TIE_NIF_PK PRIMARY KEY(NIF);
DESCRIBE TIENDAS;

ALTER TABLE TIENDAS ADD CONSTRAINT TIE_PROVINCI_CH CHECK(PROVINCIA = UPPER(PROVINCIA));
SELECT * FROM user_constraints where table_name='TIENDAS';

ALTER TABLE TIENDAS MODIFY NOMBRE VARCHAR2(30)NOT NULL;
DESCRIBE TIENDAS;

CREATE TABLE FABRICANTES(
    COD_FABRICANTE NUMBER(3),
    NOMBRE VARCHAR2(15),
    PAIS VARCHAR2(15),
    CONSTRAINT FAB_CODFAB_PK PRIMARY KEY(COD_FABRICANTE),
    CONSTRAINT FAB_NOM_CK CHECK(NOMBRE = UPPER(NOMBRE)),
    CONSTRAINT FAB_PAIS_CK CHECK(PAIS = UPPER(PAIS)) 
);
DESCRIBE FABRICANTES;
SELECT * FROM user_constraints where table_name='FABRICANTES';

CREATE TABLE ARTICULOS(
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    PRECIO_VENTA NUMBER(6),
    PRECIO_COSTO NUMBER(6),
    EXISTENCIAS NUMBER(5),
CONSTRAINT ART_CLAVEP_PK 
    PRIMARY KEY(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
CONSTRAINT ART_COD_FABRICANTE_FK FOREIGN KEY(COD_FABRICANTE)
    REFERENCES FABRICANTES ON DELETE CASCADE, 
CONSTRAINT ART_MAYORQUE0_CK CHECK(PRECIO_VENTA > 0 AND PRECIO_COSTO > 0 AND PESO > 0),
CONSTRAINT ART_CATEGORIA_CK CHECK(CATEGORIA IN('PRIMERA', 'SEGUNDA', 'TERCERA'))
);
DESCRIBE ARTICULOS;
SELECT * FROM user_constraints where table_name='ARTICULOS';

CREATE TABLE VENTAS(
    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS NUMBER(4),
CONSTRAINT VENT_CLAVEP_PK
    PRIMARY KEY(NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA),
CONSTRAINT VENT_NIF_FK FOREIGN KEY(NIF) REFERENCES TIENDAS ON DELETE CASCADE,
CONSTRAINT VENT_CLAVEF_FK FOREIGN KEY(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) 
    REFERENCES ARTICULOS ON DELETE CASCADE,
CONSTRAINT VENT_MAYORQUE0_CK CHECK(UNIDADES_VENDIDAS > 0),
CONSTRAINT VENT_CATEGORIA_CK CHECK(CATEGORIA IN('PRIMERA', 'SEGUNDA', 'TERCERA'))
);
DESCRIBE VENTAS;
SELECT * FROM user_constraints where table_name='VENTAS';

CREATE TABLE PEDIDOS(
    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    FECHA_PEDIDO DATE,
    UNIDADES_PEDIDAS NUMBER(4),
    EXISTENCIAS NUMBER(5),
CONSTRAINT PED_CLAVEP_PK
    PRIMARY KEY(NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
CONSTRAINT PED_NIF_FK FOREIGN KEY(NIF) REFERENCES TIENDAS ON DELETE CASCADE,
CONSTRAINT PED_CLAVEF_FK FOREIGN KEY(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) 
    REFERENCES ARTICULOS ON DELETE CASCADE,
CONSTRAINT PED_MAYORQUE0_CK CHECK(UNIDADES_PEDIDAS > 0),
CONSTRAINT PED_CATEGORIA_CK CHECK(CATEGORIA IN('PRIMERA', 'SEGUNDA', 'TERCERA'))
);
DESCRIBE PEDIDOS;
SELECT * FROM user_constraints where table_name='PEDIDOS';

ALTER TABLE TIENDAS ADD CONSTRAINT TIE_PRIMERAMAYUS CHECK (NOMBRE = INITCAP(NOMBRE));

ALTER TABLE PEDIDOS MODIFY UNIDADES_PEDIDAS NUMBER(6);
ALTER TABLE VENTAS MODIFY UNIDADES_VENDIDAS NUMBER(6);
ALTER TABLE TIENDAS ADD CONSTRAINT TIE_PROVINCIA_TO CHECK (PROVINCIA != 'TOLEDO');
ALTER TABLE PEDIDOS ADD (PVP NUMBER (9));
ALTER TABLE VENTAS  ADD (PVP NUMBER (9));
